name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - uses: pre-commit/action@v3.0.1

  tests:
    name: "Core py${{ matrix.python-version }} sphinx~=${{ matrix.sphinx-version }} ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Set on "false" to get the results of ALL builds
      matrix:
        os: ["ubuntu-latest"]
        # 3.9.8 seems to be broken with type_ast
        # https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1829077.html
        python-version: ["3.8", "3.11"]
        sphinx-version: ["6.0", "7.0"]
        include:
          - os: "ubuntu-latest"
            python-version: "3.11"
            sphinx-version: "8.0"
          - os: "windows-latest"
            python-version: "3.8"
            sphinx-version: "6.0"
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install sphinx~=${{ matrix.sphinx-version }} -e .[test]
          python -m pip freeze
      - name: Run pytest
        run: python -m pytest -v --cov=src --cov-report=xml --cov-report=term-missing tests

  check:
  
    # This job does nothing and is only used for the branch protection
    # see https://github.com/marketplace/actions/alls-green#why

    if: always()

    needs:
    - lint
    - tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
